[package]
name = "rustips"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rand" = "0.8.5"
"toml" = "0.5.8"
serde = "1.0.136"
serde_derive = "1.0.136"